<?php

return [
    'beginner' => [
        'key' => 'beginner',
        'label' => '初級',
        'description' => 'Laravel と関連技術の基礎を整え、バックエンドとフロントが連携する土台を固めます。',
        'color' => 'beginner',
        'lessons' => [
            ['number' => '01', 'route' => 'lesson01', 'exercise' => 'exercises.lesson01', 'title' => '環境構築と Git フロー', 'type' => '環境 / Git', 'topics' => ['Docker', 'GitHub Flow', 'Debugbar']],
            ['number' => '02', 'route' => 'lesson02', 'exercise' => 'exercises.lesson02', 'title' => 'ルーティングとコントローラ設計', 'type' => 'REST / Middleware', 'topics' => ['Routing', 'Resource', 'Middleware']],
            ['number' => '03', 'route' => 'lesson03', 'exercise' => 'exercises.lesson03', 'title' => 'モデルとデータ設計', 'type' => 'DB / Eloquent', 'topics' => ['Migration', 'Seeder', 'Eloquent']],
            ['number' => '04', 'route' => 'lesson04', 'exercise' => 'exercises.lesson04', 'title' => 'N+1 とパフォーマンス最適化', 'type' => 'Performance', 'topics' => ['Eager Loading', 'Cache', 'Telescope']],
            ['number' => '05', 'route' => 'lesson05', 'exercise' => 'exercises.lesson05', 'title' => 'バリデーションとエラーハンドリング', 'type' => 'FormRequest / Logging', 'topics' => ['FormRequest', 'Exception', 'Logging']],
            ['number' => '06', 'route' => 'lesson06', 'exercise' => 'exercises.lesson06', 'title' => '認証・認可・セキュリティ基盤', 'type' => 'Auth / Policy', 'topics' => ['Sanctum', 'Policy', 'Security']],
            ['number' => '07', 'route' => 'lesson07', 'exercise' => 'exercises.lesson07', 'title' => 'テスト駆動開発と品質保証', 'type' => 'Testing', 'topics' => ['PHPUnit', 'Mock', 'CI/CD']],
            ['number' => '08', 'route' => 'lesson08', 'exercise' => 'exercises.lesson08', 'title' => 'API 設計とバージョニング', 'type' => 'API / Docs', 'topics' => ['API Resource', 'Versioning', 'OpenAPI']],
            ['number' => '09', 'route' => 'lesson09', 'exercise' => 'exercises.lesson09', 'title' => 'ジョブと非同期処理', 'type' => 'Queue / Batch', 'topics' => ['Queue', 'Horizon', 'Schedule']],
            ['number' => '10', 'route' => 'lesson10', 'exercise' => 'exercises.lesson10', 'title' => 'デプロイと運用保守', 'type' => 'Ops / Monitoring', 'topics' => ['Deploy', 'Observability', 'Incident']],
            ['number' => '11', 'route' => 'lesson11', 'exercise' => 'exercises.lesson11', 'title' => 'Blade コンポーネントと UI 基礎', 'type' => 'View / UI', 'topics' => ['Blade', 'BEM', 'Accessibility']],
            ['number' => '12', 'route' => 'lesson12', 'exercise' => 'exercises.lesson12', 'title' => 'アルゴリズム的思考と Eloquent 応用', 'type' => 'Data Handling', 'topics' => ['Query Builder', 'Pagination', 'Collections']],
            ['number' => '13', 'route' => 'lesson13', 'exercise' => 'exercises.lesson13', 'title' => 'フロントとの連携: Inertia & API', 'type' => 'Front / API', 'topics' => ['Inertia.js', 'SPA 基礎', 'Axios']],
            ['number' => '14', 'route' => 'lesson14', 'exercise' => 'exercises.lesson14', 'title' => '小規模プロジェクト統合', 'type' => 'Project', 'topics' => ['Scaffolding', 'ENV 設計', 'Review']],
            ['number' => '15', 'route' => 'lesson15', 'exercise' => 'exercises.lesson15', 'title' => '総合演習と振り返り', 'type' => 'Recap', 'topics' => ['Review', 'Checklist', 'Next Step']],
        ],
    ],

    'intermediate' => [
        'key' => 'intermediate',
        'label' => '中級',
        'description' => 'API とフロントエンドを結合した実務的なアプリ設計を学び、チーム開発で使えるスキルを磨きます。',
        'color' => 'intermediate',
        'lessons' => [
            ['number' => '01', 'route' => 'intermediate.lesson01', 'exercise' => 'intermediate.exercises.lesson01', 'title' => 'ドメイン駆動のモジュール設計', 'type' => 'Domain / Service', 'topics' => ['UseCase', 'Service Layer', 'DTO']],
            ['number' => '02', 'route' => 'intermediate.lesson02', 'exercise' => 'intermediate.exercises.lesson02', 'title' => 'API 認証とフロントエンド統合', 'type' => 'Auth / Front', 'topics' => ['SPA Auth', 'CSRF', 'Token Refresh']],
            ['number' => '03', 'route' => 'intermediate.lesson03', 'exercise' => 'intermediate.exercises.lesson03', 'title' => 'GraphQL と REST のハイブリッド設計', 'type' => 'API Design', 'topics' => ['GraphQL', 'Schema Stitching', 'Caching']],
            ['number' => '04', 'route' => 'intermediate.lesson04', 'exercise' => 'intermediate.exercises.lesson04', 'title' => 'リアルタイム通知基盤', 'type' => 'Realtime', 'topics' => ['WebSocket', 'Broadcasting', 'Echo']],
            ['number' => '05', 'route' => 'intermediate.lesson05', 'exercise' => 'intermediate.exercises.lesson05', 'title' => 'フロントビルドと Vite 最適化', 'type' => 'Front Build', 'topics' => ['Vite', 'Code Splitting', 'Performance']],
            ['number' => '06', 'route' => 'intermediate.lesson06', 'exercise' => 'intermediate.exercises.lesson06', 'title' => '統合テストと Cypress', 'type' => 'E2E Testing', 'topics' => ['Cypress', 'Mock Server', 'CI Integration']],
            ['number' => '07', 'route' => 'intermediate.lesson07', 'exercise' => 'intermediate.exercises.lesson07', 'title' => 'API バージョン管理とドキュメント運用', 'type' => 'API Ops', 'topics' => ['Stoplight', 'Contracts', 'SDK']],
            ['number' => '08', 'route' => 'intermediate.lesson08', 'exercise' => 'intermediate.exercises.lesson08', 'title' => 'サーバーレス連携とジョブ設計', 'type' => 'Integration', 'topics' => ['Serverless', 'Queues', 'Retry']],
            ['number' => '09', 'route' => 'intermediate.lesson09', 'exercise' => 'intermediate.exercises.lesson09', 'title' => 'マイクロフロントエンド導入', 'type' => 'Front Architecture', 'topics' => ['Module Federation', 'Design System', 'CI Pipelines']],
            ['number' => '10', 'route' => 'intermediate.lesson10', 'exercise' => 'intermediate.exercises.lesson10', 'title' => 'チーム開発のコード品質管理', 'type' => 'Team Dev', 'topics' => ['Code Review', 'Static Analysis', 'CI Policy']],
            ['number' => '11', 'route' => 'intermediate.lesson11', 'exercise' => 'intermediate.exercises.lesson11', 'title' => 'API Gateway と BFF パターン', 'type' => 'Architecture', 'topics' => ['BFF', 'Gateway', 'Security']],
            ['number' => '12', 'route' => 'intermediate.lesson12', 'exercise' => 'intermediate.exercises.lesson12', 'title' => 'Feature Flag とリリース戦略', 'type' => 'Release', 'topics' => ['Feature Flag', 'Canary', 'A/B Test']],
            ['number' => '13', 'route' => 'intermediate.lesson13', 'exercise' => 'intermediate.exercises.lesson13', 'title' => '複雑なフォームと UI 状態管理', 'type' => 'Front UX', 'topics' => ['State Machine', 'UX Writing', 'Validation']],
            ['number' => '14', 'route' => 'intermediate.lesson14', 'exercise' => 'intermediate.exercises.lesson14', 'title' => 'Observability とチューニング実践', 'type' => 'Monitoring', 'topics' => ['APM', 'Query Profiling', 'Budget']],
            ['number' => '15', 'route' => 'intermediate.lesson15', 'exercise' => 'intermediate.exercises.lesson15', 'title' => '中規模プロダクト総合演習', 'type' => 'Project', 'topics' => ['Roadmap', 'Worklog', 'Retrospective']],
        ],
    ],

    'advanced' => [
        'key' => 'advanced',
        'label' => '上級',
        'description' => '大規模サービス・高トラフィック環境を想定した Laravel アーキテクチャを構築し、先進的なフロント／バック技術を統合します。',
        'color' => 'advanced',
        'lessons' => [
            ['number' => '01', 'route' => 'advanced.lesson01', 'exercise' => 'advanced.exercises.lesson01', 'title' => 'DDD × クリーンアーキテクチャ実践', 'type' => 'Architecture', 'topics' => ['DDD', 'Bounded Context', 'Clean Code']],
            ['number' => '02', 'route' => 'advanced.lesson02', 'exercise' => 'advanced.exercises.lesson02', 'title' => 'イベント駆動と CQRS', 'type' => 'Event / CQRS', 'topics' => ['CQRS', 'Event Sourcing', 'Projection']],
            ['number' => '03', 'route' => 'advanced.lesson03', 'exercise' => 'advanced.exercises.lesson03', 'title' => 'マイクロサービス連携と API Gatekeeper', 'type' => 'Microservices', 'topics' => ['gRPC', 'Service Mesh', 'Rate Control']],
            ['number' => '04', 'route' => 'advanced.lesson04', 'exercise' => 'advanced.exercises.lesson04', 'title' => '高負荷対応のキャッシング戦略', 'type' => 'Performance', 'topics' => ['Redis Cluster', 'Sidecar', 'TTL Policy']],
            ['number' => '05', 'route' => 'advanced.lesson05', 'exercise' => 'advanced.exercises.lesson05', 'title' => 'Polyglot Frontend と SSR/SSG', 'type' => 'Front Architecture', 'topics' => ['Next.js', 'SSR', 'Edge Rendering']],
            ['number' => '06', 'route' => 'advanced.lesson06', 'exercise' => 'advanced.exercises.lesson06', 'title' => 'マルチテナントとセキュリティ設計', 'type' => 'Security', 'topics' => ['Multi-Tenant', 'Row Level Security', 'Audit']],
            ['number' => '07', 'route' => 'advanced.lesson07', 'exercise' => 'advanced.exercises.lesson07', 'title' => 'Observability の自動化', 'type' => 'Observability', 'topics' => ['OpenTelemetry', 'SLO', 'Error Budget']],
            ['number' => '08', 'route' => 'advanced.lesson08', 'exercise' => 'advanced.exercises.lesson08', 'title' => 'AI サービス連携とワークフロー', 'type' => 'AI / Workflow', 'topics' => ['AI API', 'Workflow Orchestrator', 'Streaming']],
            ['number' => '09', 'route' => 'advanced.lesson09', 'exercise' => 'advanced.exercises.lesson09', 'title' => 'ゼロダウンタイムデータ移行', 'type' => 'Migration', 'topics' => ['Online Schema Change', 'Data Pipeline', 'Rollback']],
            ['number' => '10', 'route' => 'advanced.lesson10', 'exercise' => 'advanced.exercises.lesson10', 'title' => 'グローバル配信とマルチリージョン', 'type' => 'Infra', 'topics' => ['Multi Region', 'Latency Tuning', 'Failover']],
            ['number' => '11', 'route' => 'advanced.lesson11', 'exercise' => 'advanced.exercises.lesson11', 'title' => 'Edge Functions とセキュアなフロント提供', 'type' => 'Edge / Security', 'topics' => ['Edge Functions', 'CSP', 'Runtime Security']],
            ['number' => '12', 'route' => 'advanced.lesson12', 'exercise' => 'advanced.exercises.lesson12', 'title' => 'データレイク連携と分析基盤', 'type' => 'Data Platform', 'topics' => ['Data Lake', 'ELT', 'BI']],
            ['number' => '13', 'route' => 'advanced.lesson13', 'exercise' => 'advanced.exercises.lesson13', 'title' => 'SRE Culture と運用自動化', 'type' => 'Operations', 'topics' => ['SRE', 'Automation', 'Incident AI']],
            ['number' => '14', 'route' => 'advanced.lesson14', 'exercise' => 'advanced.exercises.lesson14', 'title' => 'コスト最適化と FinOps', 'type' => 'FinOps', 'topics' => ['Cost Monitoring', 'Capacity Plan', 'FinOps']],
            ['number' => '15', 'route' => 'advanced.lesson15', 'exercise' => 'advanced.exercises.lesson15', 'title' => '大規模プロダクト総合演習', 'type' => 'Capstone', 'topics' => ['Architecture Review', 'Chaos Testing', 'Postmortem']],
        ],
    ],
];
